version: '2'

services:
  local-dev:
    tty: true
    build:
      context: .
      args:
        - USER=${USER}
        - USER_PASSWORD=${USER_PASSWORD}
        - LOCAL_DEV_SSH_PUB=${LOCAL_DEV_SSH_PUB}
    image: local-dev
    platform: linux/amd64
    privileged: true
    cgroup: host
    ports:
      - "2222:22"
    env_file:
      - .envrc
    volumes:
      - type: bind
        source: ${WORKSPACE}
        target: /home/son/workspace
